package:
  name: menpodetect
  version: {{ environ['CONDACI_VERSION'] }}

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt && python setup.py sdist

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - dlib >=18.18
    - opencv >=3.1
    - menpo >=0.9.0,<0.12.0

test:
  requires:
    - pytest >=6.0,<7.0
    - pytest-cov >=2.0,<3.0
    - pytest-mock >=3.0,<4.0
    - black >= 20.0
    - libopencv *=headless*  # [linux]

  files:
    - .coveragerc

  imports:
    - menpodetect
    - menpodetect.dlib
    - menpodetect.opencv

  commands:
    - pytest $SP_DIR/menpodetect -v --cov=menpodetect --cov-config .coveragerc

about:
  home: https://github.com/menpo/menpodetect/
  license: BSD 3-Clause
  summary: The Menpo Project Python package for detecting faces
  description: |
    MenpoDetect is a Menpo Project package for detecting faces in images.
  doc_url: https://menpodetect.readthedocs.io/en/stable/
  dev_url: https://github.com/menpo/menpodetect
