package:
  name: menpodetect
  version: {{ environ['CONDACI_VERSION'] }}

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - numpy 1.9.0
    - dlib 18.10
    - menpo 0.4.0a1

test:

  imports:
    - menpodetect

about:
  home: https://github.com/menpo/menpodetect/
  license: BSD License
