name: menpo_rtd
channels:
  - conda-forge
dependencies:
  - python 3.7.*
  - setuptools

  # Docs Only
  - sphinx >=2,<3
  - sphinx_rtd_theme
  # Note that dlib and opencv are mocked otherwise readthedocs runs out of
  # memory setting up the environment
  -  menpo >=0.9,<0.12
  - pip:
      - sphinxmapxrefrole>=0.2
